### ISSUE TITLE
OWF throws unhelpful exception when theme directory not found

### ISSUE THREAD

**Issue by UberGeekxor** [ozoneplatform/owf-framework#31]
When OWF attempts to open a theme that does not exist an exception similar to the following is logged:
```
ERROR [org.codehaus.groovy.grails.web.servlet.view.GroovyPageView] Error processing GroovyPageView: Cannot invoke method exists() on null object
java.lang.NullPointerException: Cannot invoke method exists() on null object
	at ozone.owf.grails.services.ThemeService.getTheme(ThemeService.groovy:67)
	at ozone.owf.grails.services.ThemeService$getTheme.callCurrent(Unknown Source)
	at ozone.owf.grails.services.ThemeService.getCurrentTheme(ThemeService.groovy:85)
	at ozone.owf.grails.services.ThemeService$$FastClassByCGLIB$$2e630feb.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:149)
...
```

As the stack trace notes the origin of the problem is the following section in ThemeService.groovy:
```
if (!(themeName && resource.exists()))
    throw new OwfException(message: "Cannot find the requested CSS theme: ${themeName}", exceptionType: OwfExceptionTypes.GeneralServerError)
```

Adding the `?` operator before the call to the `exists()` method will allow the check to throw the cleaner `Cannot find the requested CSS theme` as intended.

**Comment by rpokorny** [comment]
It appears that this was fixed at some point.  I now get the expected error message when following the Steps to Reproduce.
