### ISSUE TITLE
Errors when deploying to JBoss

### ISSUE THREAD

**Issue by qotho** [ozoneplatform/owf-framework#49]
Are there updated deployment instructions for deploying OWF 7.16 to JBoss 7.1.1?  I tried deploying it the way we have deployed 7.14.2 in the past, but I am getting the error "NoClassDefFoundError: org/apache/tomcat/jdbc/pool/DataSource", despite configuring OWF with a Postgres datasource in OwfConfig.groovy.  I tried adding the tomcat-jdbc.jar, but it moves on to complain about other Tomcat dependencies like "org/apache/juli/logging/LogFactory".  Is Tomcat required for this version?

**Comment by ruckc** [comment]
Bump.  I'm encountering this also.

**Comment by ruckc** [comment]
```
2015-06-30 12:02:26,451 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/owf]] (ServerService Thread Pool -- 56) JBWEB000287: Exception sending context initialized event to listener instance of class org.codehaus.groovy.grails.web.context.GrailsContextLoaderListener: org.springframework.beans.factory.access.BootstrapException: Error executing bootstraps; nested exception is java.lang.NoClassDefFoundError: org/apache/tomcat/jdbc/pool/DataSourceProxy
        at org.codehaus.groovy.grails.web.context.GrailsContextLoader.initWebApplicationContext(GrailsContextLoader.java:125) [grails-web-2.3.7.jar:2.3.7]
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112) [spring-web-3.2.8.RELEASE.jar:3.2.8.RELEASE]
        at org.apache.catalina.core.StandardContext.contextListenerStart(StandardContext.java:3339) [jbossweb-7.5.9.Final-redhat-1.jar:7.5.9.Final-redhat-1]
        at org.apache.catalina.core.StandardContext.start(StandardContext.java:3780) [jbossweb-7.5.9.Final-redhat-1.jar:7.5.9.Final-redhat-1]
        at org.jboss.as.web.deployment.WebDeploymentService.doStart(WebDeploymentService.java:163) [jboss-as-web-7.5.1.Final-redhat-3.jar:7.5.1.Final-redhat-3]
        at org.jboss.as.web.deployment.WebDeploymentService.access$000(WebDeploymentService.java:61) [jboss-as-web-7.5.1.Final-redhat-3.jar:7.5.1.Final-redhat-3]
        at org.jboss.as.web.deployment.WebDeploymentService$1.run(WebDeploymentService.java:96) [jboss-as-web-7.5.1.Final-redhat-3.jar:7.5.1.Final-redhat-3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [rt.jar:1.8.0_45]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [rt.jar:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [rt.jar:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [rt.jar:1.8.0_45]
        at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_45]
        at org.jboss.threads.JBossThread.run(JBossThread.java:122)
Caused by: java.lang.NoClassDefFoundError: org/apache/tomcat/jdbc/pool/DataSourceProxy
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) [rt.jar:1.8.0_45]
        at java.lang.Class.getDeclaredMethods(Class.java:1975) [rt.jar:1.8.0_45]
        ... 9 more
Caused by: java.lang.ClassNotFoundException: org.apache.tomcat.jdbc.pool.DataSourceProxy from [Module "deployment.ozone-7.16.0.war:main" from Service Module Loader]
        at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:213) [jboss-modules.jar:1.3.6.Final-redhat-1]
        at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:459) [jboss-modules.jar:1.3.6.Final-redhat-1]
        at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:408) [jboss-modules.jar:1.3.6.Final-redhat-1]
        at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:389) [jboss-modules.jar:1.3.6.Final-redhat-1]
        at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:134) [jboss-modules.jar:1.3.6.Final-redhat-1]
        ... 11 more
```

**Comment by ruckc** [comment]
Depending on how I try configuring the datasources, i also get the below stacktrace.  This attempt was with this OwfConfig.groovy:

```
environments {
  production {
    dataSource {
      pooled = true
      dbCreate = "none"
      username = "owf7"
      password = "password"
      driverClassName = "org.postgresql.Driver"
      url = "jdbc:postgresql://localhost:5432/owf7"
      dialect = "org.hibernate.dialect.PostgreSQLDialoect"
      properties {
        minEvictableIdleTimeMillis = 180000
        timeBetweenEvictionRunsMillis = 180000
        numTestsPerEvictionRun = 3
        testOnBorrow = true
        testWhileIdle = true
        testOnReturn = true
        validationQuery = "SELECT 1"
      }
    }
  }
}
```

```
2015-06-30 13:44:25,840 INFO [org.codehaus.groovy.grails.plugins.datasource.DataSourceGrailsPlugin] (ServerService Thread Pool -- 61) [RuntimeConfiguration] Configuring data source for environment: PRODUCTION
2015-06-30 13:44:25,842 ERROR [org.codehaus.groovy.grails.web.context.GrailsContextLoader] (ServerService Thread Pool -- 61) Error initializing the application: org/apache/tomcat/jdbc/pool/DataSource: java.lang.NoClassDefFoundError: org/apache/tomcat/jdbc/pool/DataSource
        at grails.spring.BeanBuilder.invokeBeanDefiningClosure(BeanBuilder.java:754) [grails-spring-2.3.7.jar:2.3.7]
        at grails.spring.BeanBuilder.beans(BeanBuilder.java:584) [grails-spring-2.3.7.jar:2.3.7]
        at grails.spring.BeanBuilder.invokeMethod(BeanBuilder.java:527) [grails-spring-2.3.7.jar:2.3.7]
        at org.jboss.as.web.deployment.WebDeploymentService.doStart(WebDeploymentService.java:163) [jboss-as-web-7.5.1.Final-redhat-3.jar:7.5.1.Final-redhat-3]
        at org.jboss.as.web.deployment.WebDeploymentService.access$000(WebDeploymentService.java:61) [jboss-as-web-7.5.1.Final-redhat-3.jar:7.5.1.Final-redhat-3]
        at org.jboss.as.web.deployment.WebDeploymentService$1.run(WebDeploymentService.java:96) [jboss-as-web-7.5.1.Final-redhat-3.jar:7.5.1.Final-redhat-3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [rt.jar:1.8.0_45]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [rt.jar:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [rt.jar:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [rt.jar:1.8.0_45]
        at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_45]
        at org.jboss.threads.JBossThread.run(JBossThread.java:122)
Caused by: java.lang.ClassNotFoundException: org.apache.tomcat.jdbc.pool.DataSource from [Module "deployment.ozone-7.16.0.war:main" from Service Module Loader]
        at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:213) [jboss-modules.jar:1.3.6.Final-redhat-1]
        at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:459) [jboss-modules.jar:1.3.6.Final-redhat-1]
        at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:408) [jboss-modules.jar:1.3.6.Final-redhat-1]
        at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:389) [jboss-modules.jar:1.3.6.Final-redhat-1]
        at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:134) [jboss-modules.jar:1.3.6.Final-redhat-1]
        ... 12 more


```

**Comment by ruckc** [comment]
Looks like this comes from [grails-core 2.3.7](https://github.com/grails/grails-core/blob/v2.3.7/grails-plugin-datasource/src/main/groovy/org/codehaus/groovy/grails/plugins/datasource/DataSourceGrailsPlugin.groovy).  When `pooled = true` it always uses Tomcat's DataSource

**Comment by ruckc** [comment]
And, the grails-plugin-datasource requires tomcat-jdbc and tomcat-embed-logging-log4j (or tomcat-embed-logging-juli)

**Comment by rpokorny** [comment]
@mparizernc and I are working through this currently. The issue is that Grails is supposed to add tomcat-jdbc.jar and its dependencies to the war, but our BuildConfig.groovy has a line that inadvertently prevents that

**Comment by mparizernc** [comment]
Sorry for the delay.  We have determined a fix to the issue and will incorporate the fix in our next release. However in the meantime here is a workaround that should get you working with JBoss. Please take the following 3 jars and place them in the WEB-INF/lib directory under the exploded war.

tomcat-embed-logging-log4j-7.0.50.jar  - http://search.maven.org/remotecontent?filepath=org/apache/tomcat/embed/tomcat-embed-logging-log4j/7.0.50/tomcat-embed-logging-log4j-7.0.50.jar
tomcat-jdbc-7.0.50.jar - http://search.maven.org/remotecontent?filepath=org/apache/tomcat/tomcat-jdbc/7.0.50/tomcat-jdbc-7.0.50.jar
tomcat-juli-7.0.50.jar - http://search.maven.org/remotecontent?filepath=org/apache/tomcat/tomcat-juli/7.0.50/tomcat-juli-7.0.50.jar

**Comment by ruckc** [comment]
Great.  Thanks.
