### ISSUE TITLE
Error when running create-web-bundles.bat

### ISSUE THREAD

**Issue by qotho** [ozoneplatform/owf-framework#51]
I'm getting the following error when I run create-web-bundles.bat in 7.16.  Based on the ozone-developers Google group, it looks like it is an existing problem that hasn't been fixed.

Ref: ozone-developers Google group discussion
https://groups.google.com/d/msg/ozone-developers/Aoo5hEwNBBw/-aCMy_GA26QJ

```
   [exec] applying version 7.16.0-309137346
     [exec] Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/tools/ant/BuildLogger
     [exec]     at java.lang.Class.getDeclaredConstructors0(Native Method)
     [exec]     at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
     [exec]     at java.lang.Class.getDeclaredConstructors(Unknown Source)
     [exec]     at org.codehaus.groovy.reflection.CachedClass$2$1.run(CachedClass.java:69)
     [exec]     at java.security.AccessController.doPrivileged(Native Method)
     [exec]     at org.codehaus.groovy.reflection.CachedClass$2.initValue(CachedClass.java:66)
     [exec]     at org.codehaus.groovy.reflection.CachedClass$2.initValue(CachedClass.java:64)
     [exec]     at org.codehaus.groovy.util.LazyReference.getLocked(LazyReference.java:46)
     [exec]     at org.codehaus.groovy.util.LazyReference.get(LazyReference.java:33)
     [exec]     at org.codehaus.groovy.reflection.CachedClass.getConstructors(CachedClass.java:258)
     [exec]     at groovy.lang.MetaClassImpl.<init>(MetaClassImpl.java:190)
     [exec]     at groovy.lang.MetaClassImpl.<init>(MetaClassImpl.java:194)
     [exec]     at groovy.lang.MetaClassRegistry$MetaClassCreationHandle.createNormalMetaClass(MetaClassRegistry.java:158)
     [exec]     at groovy.lang.MetaClassRegistry$MetaClassCreationHandle.createWithCustomLookup(MetaClassRegistry.java:148)
     [exec]     at groovy.lang.MetaClassRegistry$MetaClassCreationHandle.create(MetaClassRegistry.java:131)
     [exec]     at org.codehaus.groovy.reflection.ClassInfo.getMetaClassUnderLock(ClassInfo.java:175)
     [exec]     at org.codehaus.groovy.reflection.ClassInfo.getMetaClass(ClassInfo.java:192)
     [exec]     at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.getMetaClass(MetaClassRegistryImpl.java:255)
     [exec]     at org.codehaus.groovy.runtime.InvokerHelper.getMetaClass(InvokerHelper.java:806)
     [exec]     at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallConstructorSite(CallSiteArray.java:84)
     [exec]     at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
     [exec]     at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182)
     [exec]     at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:186)
     [exec]     at com.studentsonly.grails.plugins.uiperformance.util.CreateWebBundles$__clinit__closure3.doCall(CreateWebBundles.
     [exec]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
     [exec]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
     [exec]     at java.lang.reflect.Method.invoke(Unknown Source)
     [exec]     at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
     [exec]     at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
     [exec]     at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:272)
     [exec]     at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:910)
     [exec]     at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:848)
     [exec]     at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:831)
     [exec]     at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodN(ScriptBytecodeAdapter.java:164)
     [exec]     at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeClosure(ScriptBytecodeAdapter.java:570)
     [exec]     at com.studentsonly.grails.plugins.uiperformance.util.CreateWebBundles.main(CreateWebBundles.groovy:105)
     [exec] Caused by: java.lang.ClassNotFoundException: org.apache.tools.ant.BuildLogger
     [exec]     at java.net.URLClassLoader.findClass(Unknown Source)
     [exec]     at java.lang.ClassLoader.loadClass(Unknown Source)
     [exec]     at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
     [exec]     at java.lang.ClassLoader.loadClass(Unknown Source)
     [exec]     ... 37 more
     [exec]         1 dir(s) moved.
```

**Comment by rpokorny** [comment]
Fixed and awaiting testing

**Comment by mparizernc** [comment]
Verified the build error has been resolved and the correct files are rebuilt.
